@baseUrl = http://localhost:3000

### ======================================================
### LOGIN
### ======================================================

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "user_email": "admin@email.com",
  "user_senha": "Admin@123"
}
